M48
; DRILL file {KiCad (7.0.0)} date Sat Nov 11 15:55:24 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-11T15:55:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.375
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C7.200
%
G90
G05
T1
X111.27Y-61.665
X117.05Y-61.665
T2
X121.084Y-85.61
X122.1Y-90.69
X123.116Y-85.61
T3
X119.56Y-87.515
X119.56Y-90.69
X124.64Y-87.515
X124.64Y-90.69
T4
X111.77Y-101.36
T0
M30
